### DISCUSSION TITLE
Urara Roadmap 2022.9~

### DISCUSSION THREAD

**Discussion by kwaa** [importantimport/urara#33] [Show and tell]
I tried to make some of my to-do items public outside of the [project](https://github.com/orgs/importantimport/projects/1).

Its design has matured enough after a year of evolution - it won't be significantly modified until it's completely rewritten, and I'll focus on the "Powerful" bit.

## Migrate to New SvelteKit Routes

No more words are needed.

## Integration with Indiekit

In the [previous discussion](https://github.com/importantimport/urara/discussions/31), I mentioned `remark-fff`, which will later be pre-installed in Urara.

Also I will try to make a `@inditkit/preset-fff` for the benefit of Urara and all future FFF compatible blogs.

## FFF Object Media

It's time to bring `alt` back! Using object media will allow you to set every detail.

string media is still compatible via `remark-fff`.

```yaml
# image
image:
  src: 'https://example.com/img.png'
  alt: 'foo bar'

# multi-image
image:
  - src: 'https://example.com/img1.png'
    alt: 'foo'
  - src: 'https://example.com/img2.png'
    alt: 'bar'
```

## `urara.ts` as Vite Plugin

Integrate it into Vite to skip the tsc conversion process and be more concise.

But I still can't finish #4.

## ~~Try `vite-imagetools`~~

~~Looking forward to it for a long time!~~

~~I may not be able to integrate successfully, so just trying.~~

## RAM Usage Optimization

This is mostly a Vite issue, but I can try to see if I can get it to work a little better.

## btw

If you have ideas, feel free to contribute or suggest to Urara.
